project:
  type: website
  output-dir: docs

website:
  title: "Hugo Lortie-Forgues"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
      - teaching.qmd
      - talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



