project:
  type: website
  output-dir: docs

website:
  title: "Hugo Lortie-Forgues"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- text: "Stats Blog"
      #  href: https://hugueslortieforgues.github.io/BlogHugo/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



